-- create new database for analytics
CREATE DATABASE OLIST_ANALYTICS;

-- DEV database
CREATE DATABASE OLIST_ANALYTICS_DEV;

-- TEST database
CREATE DATABASE OLIST_ANALYTICS_TEST;



--##-- SNOWFLAKE ROLES

-- ANALYST role READ from Prod
CREATE ROLE ANALYST;
GRANT USAGE ON DATABASE OLIST_ANALYTICS TO ROLE ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE OLIST_ANALYTICS TO ROLE ANALYST;
GRANT SELECT ON ALL TABLES IN DATABASE OLIST_ANALYTICS TO ROLE ANALYST;
-- ANALYST role full access to DEV database
GRANT ALL PRIVILEGES ON DATABASE OLIST_ANALYTICS_DEV TO ROLE ANALYST;
-- get compute
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ANALYST;
-- to read raw data
GRANT USAGE ON DATABASE OLIST_RAW TO ROLE ANALYST;
GRANT USAGE ON SCHEMA OLIST_RAW.DATA TO ROLE ANALYST; 
GRANT SELECT ON ALL TABLES IN SCHEMA OLIST_RAW.DATA TO ROLE ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OLIST_RAW.DATA TO ROLE ANALYST;


-- TRANSFORMER_PROD role has full access to PROD and TEST databases
CREATE ROLE TRANSFORMER_PROD;
GRANT ALL PRIVILEGES ON DATABASE OLIST_ANALYTICS TO ROLE TRANSFORMER_PROD;
GRANT ALL PRIVILEGES ON DATABASE OLIST_ANALYTICS_TEST TO ROLE TRANSFORMER_PROD;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORMER_PROD;
-- read raw data
GRANT USAGE ON DATABASE OLIST_RAW TO ROLE TRANSFORMER_PROD;
GRANT USAGE ON SCHEMA OLIST_RAW.DATA TO ROLE TRANSFORMER_PROD; 
GRANT SELECT ON ALL TABLES IN SCHEMA OLIST_RAW.DATA TO ROLE TRANSFORMER_PROD;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OLIST_RAW.DATA TO ROLE TRANSFORMER_PROD;






--##-- SNOWFLAKE USERS

-- PROD user with TRANSFORMER_PROD role
CREATE USER dbt_prod_service_user
    PASSWORD = 'StrongPassword123!' -- In real life, use Key Pair Auth
    DEFAULT_ROLE = TRANSFORMER_PROD
    DEFAULT_WAREHOUSE = COMPUTE_WH -- In real life different database than main/dev
    MUST_CHANGE_PASSWORD = FALSE; -- Crucial: Robots can't change passwords

-- Grant the TRANSFORMER_PROD Role to the User
GRANT ROLE TRANSFORMER_PROD TO USER dbt_prod_service_user;



-- DEV user with ANALYST role
CREATE USER dev
    PASSWORD = 'StrongPassword123!' -- In real life, use Key Pair Auth
    DEFAULT_ROLE = ANALYST
    DEFAULT_WAREHOUSE = COMPUTE_WH -- In real life different database than main/dev
    MUST_CHANGE_PASSWORD = FALSE; -- For simplicity, no password change.

-- Grant the ANALYST Role to the User
GRANT ROLE ANALYST TO USER dev;